"""Add group to Session

Revision ID: 92c7bcc6fe9a
Revises: 84fdf9832578
Create Date: 2025-10-30 00:49:43.377586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c7bcc6fe9a'
down_revision = '84fdf9832578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.drop_column('group')

    # ### end Alembic commands ###
